import React, { useState, useEffect } from 'react';
import { 
  Building, 
  Users, 
  TrendingUp, 
  DollarSign, 
  MessageSquare, 
  Send, 
  RefreshCw, 
  Search, 
  Filter, 
  Lock, 
  Shield, 
  CheckCircle, 
  XCircle, 
  AlertTriangle, 
  Calendar, 
  Mail, 
  User, 
  Activity, 
  Info, 
  Briefcase, 
  FileText,
  Clock
} from 'lucide-react';
import { useLanguage } from '../LanguageContext.js';
import { SuperAdminCompanyData, SupportTicket, SystemHealthStatus, PlatformAuditLog } from '../types.js';

interface SuperAdminViewProps {
  token: string | null;
  getHeaders: () => Record<string, string>;
}

// Translations dictionary internal to this file to preserve strict encapsulation
const adminDict: Record<string, Record<string, string>> = {
  en: {
    ownerTitle: "Owner Control Center",
    ownerSub: "Secure SaaS Platform Management Console",
    privacyAlert: "PRIVACY POLICY BOUNDARY: In strict compliance with GDPR and multi-tenant security guidelines, platform owners cannot access confidential business data (products, sales checkout lists, CRM logs, employee registers, or expenses) of tenant enterprises.",
    syncData: "Sync Platform Data",
    syncing: "Synchronizing nodes...",
    
    // Sub-modules navigation
    tabOverview: "Overview Panel",
    tabCompanies: "Customer Companies",
    tabSubscriptions: "Subscription Management",
    tabAnalytics: "Platform Analytics",
    tabCustomers: "Platform Customers",
    tabSupport: "Support Helpdesk",
    tabFinancials: "Owner Financials",
    tabPrivacy: "Privacy Protections",

    // KPI labels
    kpiRegistered: "Total Companies",
    kpiActive: "Active Companies",
    kpiSuspended: "Suspended Companies",
    kpiUsers: "Total Platform Users",
    kpiSubscriptions: "Total Subscriptions",
    kpiMrr: "Monthly Revenue (MRR)",
    kpiArr: "Annual Projected Yield (ARR)",
    kpiSupport: "Active Support Requests",

    // Actions & Buttons
    viewBrief: "View Profile",
    ajPlan: "Adjust Plan",
    saveSettings: "Apply Configuration",
    discardChanges: "Cancel",
    closeTkt: "Close Ticket",
    repliedStatus: "Resolved",
    closeTktSuccess: "Ticket closed and resolved.",
    tktReplies: "Support Conversation Track",
    sendReplyBtn: "Send Resolution Guide",
    noTkts: "All client inquiries are resolved! Clear support queue.",
    
    // Privacy labels
    privBadge: "GDPR Compliant & Cryptographically Isolated",
    privHeader: "Platform Isolation Rule Ledger",
    privRule1: "Horizontal database isolation partitions all product schemas of customer cafes, pharmacies, and stores.",
    privRule2: "Platform Owner can adjust tenant system access states, but can NEVER read private billing invoices.",
    privRule3: "Client checkout ledger data is strictly un-scannable and secure with zero bypass permissions.",

    // Extended keys for 100% full translation coverage
    corporateId: "Corporate ID",
    enterpriseName: "Enterprise Name",
    ownerName: "Owner Name",
    regDate: "Registration Date",
    accessLevel: "Tenant Access Level",
    lastActivity: "Last Activity Date",
    activeUsers: "Active Users",
    status: "Status",
    actions: "Control Actions",
    searchQueryPlaceholder: "Filter company names, owner identifiers, IDs...",
    allPlans: "All Plans",
    allStatuses: "All Statuses",
    companyOwner: "Company Owner",
    businessEmail: "Business Email",
    assignedCompany: "Assigned Company",
    plan: "Subscription Plan",
    deleteUser: "Delete user",
    supportInboxes: "Communications Helpdesk Inboxes",
    supportInboxesSub: "Review tickets generated by client managers weekly",
    viewProfileTitle: "Secure Node Profile",
    tenantDbIsolation: "TENANT DATABASE ISOLATION ON",
    tenantDbIsolationText: "Under tenant sandbox compliance controls, business inventory records, POS transactions history, staff salary lists, and customer CRM databases are stored in cryptographically isolated rows. This profile only shows system-level configuration metadata.",
    closeProfileBriefing: "Close Profile Briefing",
    originalQuery: "Original Client Query",
    ticketId: "Ticket ID",
    category: "Category",
    fromUser: "From user",
    onOrg: "on organization",
    supportResolved: "Support Ticket marked as Resolved, closed and secure!",
    selectSupportPrompt: "Select an active support center ticket to inspect discussion history.",
    treasuryTitle: "Owner Treasury Balance Sheet",
    treasurySub: "Platform gross yield indices based on calculated workspace subscriptions.",
    monthlyCashflow: "Monthly Cashflow",
    netSubscriptionMRR: "Net Subscription MRR",
    annualizedMarginRun: "Annualized Margin Run",
    calculatedProjectedYield: "Calculated projected yield",
    projectedQ3Forecast: "Projected Q3 Forecast",
    subscriptionCompoundEstimate: "Subscription compound estimate",
    monthlyGrowthRate: "Monthly growth rate",
    projections12Month: "SaaS Platform 12-Month Projections",
    projectionsDesc: "Cashflow trajectories account for a steady user conversion increase with structural server maintenance and hosting outlays fully offset. Projections assume a 2.4% yearly customer churn.",
    freePlanUsers: "Free Plan Users",
    businessPlanSubscribers: "Business Plan Subscribers",
    premiumPlanSubscribers: "Premium Plan Subscribers",
    revenueYields: "Yields",
    platformVolume: "platform volume",
    cashflowYieldModel: "SaaS Cashflow Yield Model",
    cashflowYieldModelSub: "Platform-level estimations of recurring revenue, user expansion logs, and conversion tracking coefficients.",
    growthAnalysis: "Compounding Growth Analysis",
    monthlyRecurringVolume: "Monthly Recurring Revenue Volume:",
    compactedGrowthIndex: "Compacted Growth Index:",
    subConversionCoefficient: "Subscription conversion coefficient:",
    subTrialAttrition: "Subscription trial attrition factor:",
    conversionRateInsight: "Conversion rate insight",
    conversionRateText: "Conversion tracking shows that offering automated Telegram alerts and integrated smart inventory limits provides the highest incentive for Free trials to purchase a plan.",
    saasProjectionsTitle: "SaaS Projections",
    saasProjectionsText: "With a targeted promotional onboarding schedule, we project a $2,200 MRR yield by Q3.",
    mostUsedSaaS: "Most Used SaaS Modules",
    monthlyNewRegs: "Monthly New Registrations",
    growthRateVolume: "Growth Rate Volume",
    platformChurnRate: "Platform Churn Rate",
    companiesTabDesc: "Configure platform statuses, view enterprise profiles, and freeze or upgrade subscriptions.",
    customersTabDesc: "Platform-level administrator records showing company owner names and work emails. Confidential database logs remain isolated.",
    configureEnterpriseTitle: "Configure Enterprise Subscription",
    configureEnterpriseDesc: "Adjust operational system permissions and plan scopes for tenant administrators immediately.",
    workspaceSelection: "Workspace Selection",
    accountState: "Account State",
    billingStatus: "Billing Status",
    ownerBusinessInsight: "Owner Business Insight",
    ownerBusinessInsightText: "Premium monthly tier comprises the largest ratio of ARR cash volumes. Upgraded workflows from client helpdesk resolve friction to improve retention factors.",
    typeDiagnosticPrompt: "Type diagnostic recommendations or resolutions here...",
    toastTitleSuccess: "SUCCESS",
    toastTitleError: "ERROR",
    cancelButton: "Cancel"
  },
  ru: {
    ownerTitle: "Операционный центр владельца",
    ownerSub: "Панель управления SaaS-платформой",
    privacyAlert: "КОНФИДЕНЦИАЛЬНОСТЬ ДАННЫХ: В соответствии с требованиями GDPR и стандартами безопасности, администраторы платформы не имеют доступа к конфиденциальным коммерческим записям (спискам товаров, транзакциям, базам CRM, зарплатам или расходам) арендаторов.",
    syncData: "Синхронизировать данные",
    syncing: "Синхронизация...",
    
    tabOverview: "Сводка показателей",
    tabCompanies: "Компании-клиенты",
    tabSubscriptions: "Управление подписками",
    tabAnalytics: "Аналитика платформы",
    tabCustomers: "Пользователи SaaS",
    tabSupport: "Центр поддержки",
    tabFinancials: "Финансы владельца",
    tabPrivacy: "Защита данных",

    kpiRegistered: "Всего зарегистрировано",
    kpiActive: "Активные компании",
    kpiSuspended: "Заблокированные",
    kpiUsers: "Всего пользователей",
    kpiSubscriptions: "Платных подписок",
    kpiMrr: "Ежемесячный доход (MRR)",
    kpiArr: "Годовой доход (ARR)",
    kpiSupport: "Запросы поддержки",

    viewBrief: "Карточка",
    ajPlan: "Изменить тариф",
    saveSettings: "Сохранить настройки",
    discardChanges: "Отмена",
    closeTkt: "Закрыть тикет",
    repliedStatus: "Решен",
    closeTktSuccess: "Тикет был закрыт и помечен как решенный.",
    tktReplies: "Переписка службы поддержки",
    sendReplyBtn: "Отправить ответ",
    noTkts: "Отличная работа! Все тикеты клиентов успешно решены.",

    privBadge: "Соответствует GDPR и изолировано",
    privHeader: "Правила изоляции данных на платформе",
    privRule1: "Горизонтальная изоляция баз данных полностью разграничивает схемы товаров и транзакций клиентов.",
    privRule2: "Владелец платформы может менять тарифные уровни, но НИКОГДА не имеет технического доступа к CRM-клиентам.",
    privRule3: "Списки расходов и личные данные кассиров зашифрованы и не подлежат экспорту вне кабинета компании.",

    // Extended keys for 100% full translation coverage
    corporateId: "ID компании",
    enterpriseName: "Наименование компании",
    ownerName: "Имя владельца",
    regDate: "Дата регистрации",
    accessLevel: "Уровень тарифа",
    lastActivity: "Последняя активность",
    activeUsers: "Пользователи",
    status: "Статус",
    actions: "Действия",
    searchQueryPlaceholder: "Поиск компаний, владельцев, идентификаторов...",
    allPlans: "Все тарифы",
    allStatuses: "Все статусы",
    companyOwner: "Владелец компании",
    businessEmail: "Эл. почта бизнеса",
    assignedCompany: "Привязанная компания",
    plan: "Тарифный план",
    deleteUser: "Удалить пользователя",
    supportInboxes: "Входящие сообщения службы поддержки",
    supportInboxesSub: "Просмотр обращений, созданных управляющими компаний",
    viewProfileTitle: "Безопасный профиль ноды",
    tenantDbIsolation: "ИЗОЛЯЦИЯ БАЗ ДАННЫХ АКТИВНА",
    tenantDbIsolationText: "Согласно правилам изоляции, товарные запасы, истории продаж, списки зарплат сотрудников и CRM-базы клиентов хранятся в криптографически изолированных строках. Профиль содержит только технические метаданные системы.",
    closeProfileBriefing: "Закрыть карточку компании",
    originalQuery: "Первоначальное обращение клиента",
    ticketId: "Тикет ID",
    category: "Категория",
    fromUser: "От пользователя",
    onOrg: "в компании",
    supportResolved: "Запрос успешно решен, закрыт и заархивирован!",
    selectSupportPrompt: "Выберите активный тикет службы поддержки для просмотра истории переписки.",
    treasuryTitle: "Баланс казначейства владельца",
    treasurySub: "Валовые показатели выручки платформы на основе действующих подписок.",
    monthlyCashflow: "Ежемесячный поток средств",
    netSubscriptionMRR: "Чистая выручка MRR",
    annualizedMarginRun: "Прогнозируемый годовой оборот",
    calculatedProjectedYield: "Расчетная ожидаемая доходность",
    projectedQ3Forecast: "Ожидаемый прогноз на 3-й квартал",
    subscriptionCompoundEstimate: "Сложная оценка роста подписок",
    monthlyGrowthRate: "Темп ежемесячного роста",
    projections12Month: "Прогноз развития SaaS на 12 месяцев",
    projectionsDesc: "Траектория денежных потоков учитывает стабильный рост конверсии пользователей при полной окупаемости расходов на сервер и хостинг. Прогноз предполагает ежегодный отток клиентов в размере 2.4%.",
    freePlanUsers: "Пользователи бесплатного плана",
    businessPlanSubscribers: "Подписчики бизнес-плана",
    premiumPlanSubscribers: "Подписчики премиум-плана",
    revenueYields: "Приносит",
    platformVolume: "объема платформы",
    cashflowYieldModel: "Модель доходности денежных потоков SaaS",
    cashflowYieldModelSub: "Оценки регулярной выручки на уровне платформы, журналы расширения и показатели конверсии.",
    growthAnalysis: "Анализ сложного роста компании",
    monthlyRecurringVolume: "Ежемесячный объем регулярной выручки:",
    compactedGrowthIndex: "Индекс сводного роста:",
    subConversionCoefficient: "Коэффициент конверсии подписки:",
    subTrialAttrition: "Фактор оттока пробных подписок:",
    conversionRateInsight: "Показатели уровня конверсии",
    conversionRateText: "Отслеживание показывает, что предложение автоматических уведомлений в Telegram и умных лимитов запасов дает максимальный стимул для покупки платного тарифа.",
    saasProjectionsTitle: "Прогнозы SaaS",
    saasProjectionsText: "При плановом онбординге мы прогнозируем $2,200 MRR выручки к 3-му кварталу.",
    mostUsedSaaS: "Самые используемые модули SaaS",
    monthlyNewRegs: "Новые регистрации за месяц",
    growthRateVolume: "Объем темпа роста",
    platformChurnRate: "Уровень оттока с платформы",
    companiesTabDesc: "Настраивайте статусы платформы, открывайте карточки компаний, замораживайте или повышайте тарифы.",
    customersTabDesc: "Административные записи платформы, показывающие имена владельцев и их рабочие почты. Исходные базы данных изолированы.",
    configureEnterpriseTitle: "Настройка подписки компании",
    configureEnterpriseDesc: "Мгновенно настраивайте системные права доступа и рамки тарифа для администраторов компании.",
    workspaceSelection: "Выбранная компания",
    accountState: "Состояние аккаунта",
    billingStatus: "Статус оплаты",
    ownerBusinessInsight: "Бизнес-инсайт для владельца",
    ownerBusinessInsightText: "Премиум-тариф приносит наибольшую долю в годовой выручке ARR. Улучшение работы поддержки повышает лояльность клиентов.",
    typeDiagnosticPrompt: "Введите здесь рекомендации по диагностике или текст решения проблемы...",
    toastTitleSuccess: "УСПЕШНО",
    toastTitleError: "ОШИБКА",
    cancelButton: "Отмена"
  },
  ky: {
    ownerTitle: "Кожоюндун Башкаруу Борбору",
    ownerSub: "SaaS Платформасынын Коопсуз Консолу",
    privacyAlert: "КУПУЯЛУУЛУК КЕПИЛДИГИ: GDPR жана көп ижарачылык коопсуздук эрежелерине ылайык, платформа администратору ишканалардын ички маалыматтарына (товарлар, сатуулар, CRM маалыматтары, кызматкерлердин тизмеси же чыгымдар) кире албайт.",
    syncData: "Маалыматты Жаңыртуу",
    syncing: "Жаңыланууда...",
    
    tabOverview: "Жалпы Кароо",
    tabCompanies: "Кардар Компаниялар",
    tabSubscriptions: "Жазылууларды Башкаруу",
    tabAnalytics: "Платформа Аналитикасы",
    tabCustomers: "Платформа Колдонуучулары",
    tabSupport: "Колдоо Бөлүмү",
    tabFinancials: "Кожоюндун Кирешеси",
    tabPrivacy: "Купуялык Кепилдиктери",

    kpiRegistered: "Катталган Компаниялар",
    kpiActive: "Активдүү Кардарлар",
    kpiSuspended: "Блокдолгон Кардарлар",
    kpiUsers: "Платформа Колдонуучулары",
    kpiSubscriptions: "Жалпы Жазылуулар",
    kpiMrr: "Айлык Киреше (MRR)",
    kpiArr: "Жылдык Киреше (ARR)",
    kpiSupport: "Колдоо Сурамдары",

    viewBrief: "Анкетаны Көрүү",
    ajPlan: "Тарифти Манипуляциялоо",
    saveSettings: "Өзгөрүүлөрдү Сактоо",
    discardChanges: "Артка Кайтуу",
    closeTkt: "Тикетти Жабуу",
    repliedStatus: "Чечилди",
    closeTktSuccess: "Суроо толугу менен чечилди жана жабылды.",
    tktReplies: "Колдоо Кат Багыты",
    sendReplyBtn: "Жоопту Жөнөтүү",
    noTkts: "Бардык кардарлардын суроолору чечилди! Чат бош.",

    privBadge: "GDPR Бүтүндүгү Корголгон",
    privHeader: "Платформа ижара купуялык эрежелери",
    privRule1: "Ар бир компаниянын сатуу маалыматтары жана товар базалары техникалык деңгээлде толук бөлүнгөн.",
    privRule2: "Платформа кожоюну тарифтик абалды өзгөртө алат, бирок чектерге, маяналарга кире албайт.",
    privRule3: "Тиркемелер жана логистикалык документтер сырткы админдерге эч качан көрсөтүлбөйт.",

    // Extended keys for 100% full translation coverage
    corporateId: "Компания ID коду",
    enterpriseName: "Ишкананын аталышы",
    ownerName: "Ишкана ээсинин аты",
    regDate: "Катталган күнү",
    accessLevel: "Тарифтик деңгээли",
    lastActivity: "Акыркы аракет күнү",
    activeUsers: "Колдонуучулар",
    status: "Статусу",
    actions: "Башкаруу иштери",
    searchQueryPlaceholder: "Компаниянын аты, ээси же ID коду боюнча издөө...",
    allPlans: "Бардык тарифтер",
    allStatuses: "Бардык статустар",
    companyOwner: "Компаниянын ээси",
    businessEmail: "Бизнес эл. почтасы",
    assignedCompany: "Таандык компания",
    plan: "Жазылуу тарифи",
    deleteUser: "Колдонуучуну өчүрүү",
    supportInboxes: "Колдоо кызматынын кутучасы",
    supportInboxesSub: "Арендатор компаниялар тарабынан түзүлгөн сурамдар",
    viewProfileTitle: "Корголгон маалымат профили",
    tenantDbIsolation: "ИЖАРАЧЫ БАЗАЛАРЫНЫН ИЗОЛЯЦИЯСЫ ЖАНДЫ",
    tenantDbIsolationText: "Коопсуздук эрежелерине ылайык, товарлар, сатуулар, маяналар жана кардарлар өзүнчө корголгон катарларда сакталат. Бул профил жөн гана системалык метамаалыматтарды көрсөтөт.",
    closeProfileBriefing: "Профилди жабуу",
    originalQuery: "Кардардын баштапкы суроосу",
    ticketId: "Сурам ID",
    category: "Категориясы",
    fromUser: "Колдонуучудан",
    onOrg: "ишканада",
    supportResolved: "Колдоо суроосу толугу менен чечилди, жабылды жана корголду!",
    selectSupportPrompt: "Сүйлөшүү тарыхын көрүү үчүн активдүү колдоо сурамын тандаңыз.",
    treasuryTitle: "Кожоюндун Казна Балансы",
    treasurySub: "Жазылуулардын негизинде платформанын жалпы киреше көрсөткүчтөрү.",
    monthlyCashflow: "Айлык акча агымы",
    netSubscriptionMRR: "Таза жазылуу MRR",
    annualizedMarginRun: "Жылдык кирешенин болжолу",
    calculatedProjectedYield: "Эсептелген жылдык киреше",
    projectedQ3Forecast: "Үчүнчү чейрекке болжол",
    subscriptionCompoundEstimate: "Жазылуудан түшүүчү киреше",
    monthlyGrowthRate: "Айлык өсүү темпи",
    projections12Month: "SaaS Платформасынын 12 айлык божомолу",
    projectionsDesc: "Акча агымынын божомолу сервердик жана хостингдик чыгымдар толугу менен жабылгандан кийинки колдонуучулардын көбөйүшүн эске алат. Киреше жылына 2.4% кардар токтотуу факторун эске алуу менен түзүлдү.",
    freePlanUsers: "Акысыз тарифтин колдонуучулары",
    businessPlanSubscribers: "Бизнес тарифке жазылгандар",
    premiumPlanSubscribers: "Премиум тарифке жазылгандар",
    revenueYields: "Киреше берет",
    platformVolume: "платформа көлөмүнөн",
    cashflowYieldModel: "SaaS Акча Агымы Модели",
    cashflowYieldModelSub: "Жазылуудан түшкөн регулярдуу киреше, каттоолор жана конверсия көрсөткүчтөрүнүн баасы.",
    growthAnalysis: "Кошумча өсүү анализи",
    monthlyRecurringVolume: "Айлык кайталануучу киреше көлөмү:",
    compactedGrowthIndex: "Кыскартылган өсүү индекси:",
    subConversionCoefficient: "Жазылуунун конверсия коэффициенти:",
    subTrialAttrition: "Сыноо тарифинен кетүү коэффициенти:",
    conversionRateInsight: "Конверсия деңгээлинин көрсөткүчү",
    conversionRateText: "Изилдөөлөр көрсөткөндөй, автоматтык Telegram билдирүүлөрү жана акылдуу запас лимиттери акысыз колдонуучулардын тариф сатып алуусуна чоң өбөлгө түзөт.",
    saasProjectionsTitle: "SaaS Божомолдору",
    saasProjectionsText: "Пландуу кошуу менен биз 3-чейрекке чейин $2,200 MRR кирешесин болжолдойбуз.",
    mostUsedSaaS: "Эң көп колдонулган SaaS модулдары",
    monthlyNewRegs: "Айлык жаңы каттоолор",
    growthRateVolume: "Өсүү темпинин көлөмү",
    platformChurnRate: "Платформадан кетүүлөр коэффициенти",
    companiesTabDesc: "Система статустарын, ишкананын профилдерин өзгөртүңүз жана жазылууларды башкарыңыз.",
    customersTabDesc: "Ээлеринин аты-жөнүн жана жумушчу почталарын көрсөтүүчү реестр. Купуя маалыматтар жабык бойдон калат.",
    configureEnterpriseTitle: "Компаниянын жазылуусун тууралоо",
    configureEnterpriseDesc: "Компаниянын кассир же администраторлору үчүн системалык мүмкүнчүлүктөрдү дароо өзгөртүү.",
    workspaceSelection: "Тандалган ишкана",
    accountState: "Аккаунттун абалы",
    billingStatus: "Төлөм статусу",
    ownerBusinessInsight: "Киреше инсайты кожоюн үчүн",
    ownerBusinessInsightText: "Премиум-тариф жылдык ARR кирешесине эң чоң салым кошот. Колдоо кызматынын ишин жакшыртуу кардарлардын кетүүсүн азайтат.",
    typeDiagnosticPrompt: "Бул жерге сурам боюнча сунуш же маселени чечүү жолун жазыңыз...",
    toastTitleSuccess: "ИЙГИЛИКТҮҮ",
    toastTitleError: "КАТА",
    cancelButton: "Жокко чыгаруу"
  }
};

export default function SuperAdminView({ token, getHeaders }: SuperAdminViewProps) {
  const { language } = useLanguage();
  const t = adminDict[language] || adminDict.en;

  // Active workspace subsection selection
  const [activeSubTab, setActiveSubTab] = useState<'overview' | 'companies' | 'subscriptions' | 'analytics' | 'customers' | 'support' | 'financials'>('overview');
  
  // Custom interactive delete modal and in-app toasts
  const [companyToDelete, setCompanyToDelete] = useState<{ id: string; name: string } | null>(null);
  const [notification, setNotification] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  const showNotification = (message: string, type: 'success' | 'error' = 'success') => {
    setNotification({ message, type });
    setTimeout(() => {
      setNotification(null);
    }, 4500);
  };
  
  // States
  const [appStats, setAppStats] = useState<any | null>(null);
  const [companiesList, setCompaniesList] = useState<any[]>([]);
  const [ticketsList, setTicketsList] = useState<any[]>([]);
  const [auditLogs, setAuditLogs] = useState<PlatformAuditLog[]>([]);
  const [healthStatus, setHealthStatus] = useState<any | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  // Interaction handlers
  const [selectedCompany, setSelectedCompany] = useState<any | null>(null);
  const [detailCompany, setDetailCompany] = useState<any | null>(null);
  const [selectedTicket, setSelectedTicket] = useState<any | null>(null);
  const [ticketReply, setTicketReply] = useState('');
  const [sendingReply, setSendingReply] = useState(false);
  const [savingPlan, setSavingPlan] = useState(false);

  // Plan editor states
  const [editPlan, setEditPlan] = useState<'Free' | 'Business' | 'Premium'>('Free');
  const [editStatus, setEditStatus] = useState<'Active' | 'Suspended'>('Active');
  const [editBilling, setEditBilling] = useState<'Paid' | 'Unpaid' | 'Trial'>('Paid');

  // Search filter
  const [searchQuery, setSearchQuery] = useState('');
  const [planFilter, setPlanFilter] = useState<string>('all');
  const [statusFilter, setStatusFilter] = useState<string>('all');

  const synchronizeAdminData = async () => {
    try {
      setRefreshing(true);
      
      // Async requests to direct endpoints
      const [resStats, resCompanies, resTickets, resLogs, resHealth] = await Promise.all([
        fetch('/api/superadmin/stats', { headers: getHeaders() }),
        fetch('/api/superadmin/companies', { headers: getHeaders() }),
        fetch('/api/superadmin/tickets', { headers: getHeaders() }),
        fetch('/api/superadmin/audit-logs', { headers: getHeaders() }),
        fetch('/api/superadmin/health', { headers: getHeaders() })
      ]);

      if (resStats.ok) setAppStats(await resStats.json());
      if (resCompanies.ok) setCompaniesList(await resCompanies.json());
      if (resTickets.ok) setTicketsList(await resTickets.json());
      if (resLogs.ok) setAuditLogs(await resLogs.json());
      if (resHealth.ok) setHealthStatus(await resHealth.json());

    } catch (error) {
      console.error("SuperAdmin sync failed:", error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    synchronizeAdminData();
  }, []);

  // Modify subscriber business status
  const handleModifyCompanyPlanSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedCompany) return;
    try {
      setSavingPlan(true);
      const res = await fetch(`/api/superadmin/companies/${selectedCompany.id}/plan`, {
        method: 'POST',
        headers: getHeaders(),
        body: JSON.stringify({
          subscriptionPlan: editPlan,
          status: editStatus,
          billingStatus: editBilling
        })
      });

      if (res.ok) {
        setSelectedCompany(null);
        showNotification(
          language === 'ru' ? "Тариф успешно обновлен!" : language === 'ky' ? "Тариф ийгиликтүү жаңыртылды!" : "Subscription tier updated successfully!",
          "success"
        );
        await synchronizeAdminData();
      } else {
        const err = await res.json();
        showNotification(err.error || "Failed to adjust properties.", "error");
      }
    } catch (e) {
      console.error(e);
    } finally {
      setSavingPlan(false);
    }
  };

  // Reply to support ticket
  const handleReplyTicketSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedTicket || !ticketReply.trim()) return;
    try {
      setSendingReply(true);
      const res = await fetch(`/api/superadmin/tickets/${selectedTicket.id}/reply`, {
        method: 'POST',
        headers: getHeaders(),
        body: JSON.stringify({ text: ticketReply.trim() })
      });

      if (res.ok) {
        setTicketReply('');
        const updatedTicket = await res.json();
        setSelectedTicket(updatedTicket);
        showNotification(
          language === 'ru' ? "Ответ успешно направлен!" : language === 'ky' ? "Жооп жөнөтүлдү!" : "Support ticket answer sent!",
          "success"
        );
        await synchronizeAdminData();
      } else {
        showNotification("Failed to submit ticket reply.", "error");
      }
    } catch (e) {
      console.error(e);
    } finally {
      setSendingReply(false);
    }
  };

  // Close ticket manually
  const handleCloseTicket = async (ticketId: string) => {
    try {
      // Set resolved client-side and trigger resolution message or complete cycle
      const res = await fetch(`/api/superadmin/tickets/${ticketId}/reply`, {
        method: 'POST',
        headers: getHeaders(),
        body: JSON.stringify({ text: "[SYSTEM RESOLUTION]: Ticket successfully verified, closed and archived by the SaaS platform owner Bekzat." })
      });
      if (res.ok) {
        showNotification(t.closeTktSuccess, "success");
        setSelectedTicket(null);
        await synchronizeAdminData();
      }
    } catch (error) {
      console.error("Close ticket error:", error);
    }
  };

  const handleDeleteCompany = (companyId: string, companyName: string) => {
    setCompanyToDelete({ id: companyId, name: companyName });
  };

  const handleConfirmDeleteCompany = async () => {
    if (!companyToDelete) return;
    try {
      setRefreshing(true);
      const res = await fetch(`/api/superadmin/companies/${companyToDelete.id}`, {
        method: 'DELETE',
        headers: getHeaders()
      });
      
      if (res.ok) {
        showNotification(
          language === 'ru' 
            ? `Компания "${companyToDelete.name}" и все связанные пользователи успешно удалены!` 
            : language === 'ky'
            ? `"${companyToDelete.name}" компаниясы жана анын колдонуучулары өчүрүлдү!`
            : `Company "${companyToDelete.name}" and all elements successfully deleted!`,
          "success"
        );
        setCompanyToDelete(null);
        await synchronizeAdminData();
      } else {
        const err = await res.json();
        showNotification(err.error || "Failed to delete company.", "error");
      }
    } catch (e: any) {
      console.error(e);
      showNotification(e.message || "An error occurred.", "error");
    } finally {
      setRefreshing(false);
      setCompanyToDelete(null);
    }
  };

  // Derived platform calculations
  const totalRegisteredCompaniesCount = companiesList.length;
  const activeCompaniesCount = companiesList.filter(c => c.status === 'Active').length;
  const suspendedCompaniesCount = companiesList.filter(c => c.status === 'Suspended').length;
  const totalSaasUsersCount = companiesList.reduce((sum, c) => sum + (c.usersCount || 1), 0);
  const activePaidSubscriptionsCount = companiesList.filter(c => c.subscriptionPlan !== 'Free' && c.billingStatus === 'Paid').length;
  
  // MRR & ARR Calculations
  const platformMRR = companiesList.reduce((sum, c) => {
    if (c.billingStatus === 'Paid') {
      if (c.subscriptionPlan === 'Business') return sum + 49;
      if (c.subscriptionPlan === 'Premium') return sum + 149;
    }
    return sum;
  }, 0);
  const platformARR = platformMRR * 12;
  const totalSupportRequestsCount = ticketsList.length;

  // Subscription analytics counts
  const freePlanCount = companiesList.filter(c => c.subscriptionPlan === 'Free').length;
  const businessPlanCount = companiesList.filter(c => c.subscriptionPlan === 'Business').length;
  const premiumPlanCount = companiesList.filter(c => c.subscriptionPlan === 'Premium').length;

  // Search filter implementation
  const filteredCompanies = companiesList.filter(c => {
    const matchesSearch = c.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          c.ownerName.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          c.id.toLowerCase().includes(searchQuery.toLowerCase());
    
    const matchesPlan = planFilter === 'all' || c.subscriptionPlan === planFilter;
    const matchesStatus = statusFilter === 'all' || c.status === statusFilter;

    return matchesSearch && matchesPlan && matchesStatus;
  });

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center p-20 text-slate-500 gap-3 min-h-[400px]">
        <RefreshCw className="w-8 h-8 text-indigo-600 animate-spin" />
        <span className="text-xs font-semibold">{t.syncing}</span>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-7xl mx-auto" id="saas-owner-dashboard-container">
      
      {/* Premium Stripe/Notion style dark telemetry header */}
      <div className="bg-slate-900 text-white rounded-3xl p-6 shadow-xl border border-slate-800 relative overflow-hidden select-none">
        
        {/* Background visual geometric absolute glow */}
        <div className="absolute right-0 top-0 w-80 h-80 rounded-full bg-indigo-500/10 blur-3.5xl pointer-events-none"></div>
        <div className="absolute left-1/3 bottom-0 w-64 h-64 rounded-full bg-violet-500/5 blur-3xl pointer-events-none"></div>

        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 relative z-10">
          <div>
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 bg-indigo-650 text-[9px] font-bold uppercase rounded tracking-widest font-mono text-indigo-100">
                SaaS Owner Portal
              </span>
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
              <span className="text-[10px] text-slate-400 font-mono">Platform Identity Isolation (GDPR Lock)</span>
            </div>
            <h1 className="text-xl font-black text-white mt-1 uppercase tracking-tight flex items-center gap-2 font-sans md:text-2xl">
              <Shield className="w-6 h-6 text-indigo-400" />
              {t.ownerTitle}
            </h1>
            <p className="text-xs text-slate-400 mt-1 max-w-3xl font-serif font-light leading-relaxed">
              {t.privacyAlert}
            </p>
          </div>

          <button
            onClick={synchronizeAdminData}
            disabled={refreshing}
            className="flex items-center gap-1.5 px-4.5 py-2.5 bg-indigo-600 hover:bg-slate-855 text-white border border-indigo-500/40 rounded-xl text-xs font-bold font-sans tracking-wide cursor-pointer shadow-lg shadow-indigo-600/10 hover:shadow-none transition duration-150"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />
            {refreshing ? t.syncing : t.syncData}
          </button>
        </div>

        {/* Platform Overview KPIs Grid block - 100% platform-level, 0% tenant product/margins block */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-8 border-t border-slate-850 pt-6">
          
          <div className="p-3 bg-slate-850/40 border border-slate-800 rounded-2xl space-y-1">
            <span className="text-[10px] text-slate-400 font-bold block uppercase tracking-wider">{t.kpiRegistered}</span>
            <div className="flex items-baseline justify-between select-text">
              <span className="text-2xl font-extrabold text-white font-mono">{totalRegisteredCompaniesCount}</span>
              <span className="text-[9.5px] text-indigo-300 font-semibold font-mono">
                {language === 'ru' ? 'Компании' : language === 'ky' ? 'Ишканалар' : 'Workspaces'}
              </span>
            </div>
          </div>

          <div className="p-3 bg-slate-850/40 border border-slate-800 rounded-2xl space-y-1">
            <span className="text-[10px] text-indigo-300 font-bold block uppercase tracking-wider">{t.kpiActive}</span>
            <div className="flex items-baseline justify-between select-text">
              <span className="text-2xl font-extrabold text-emerald-400 font-mono">{activeCompaniesCount}</span>
              <span className="text-[9.5px] text-slate-400 font-mono">Live Nodes</span>
            </div>
          </div>

          <div className="p-3 bg-slate-850/40 border border-slate-800 rounded-2xl space-y-1">
            <span className="text-[10px] text-slate-405 font-bold block uppercase tracking-wider">{t.kpiSuspended}</span>
            <div className="flex items-baseline justify-between select-text">
              <span className="text-2xl font-extrabold text-rose-455 font-mono">{suspendedCompaniesCount}</span>
              <span className="text-[9.5px] text-slate-400 font-mono">Frozen</span>
            </div>
          </div>

          <div className="p-3 bg-slate-850/40 border border-slate-800 rounded-2xl space-y-1">
            <span className="text-[10px] text-slate-400 font-bold block uppercase tracking-wider">{t.kpiUsers}</span>
            <div className="flex items-baseline justify-between select-text">
              <span className="text-2xl font-extrabold text-white font-mono">{totalSaasUsersCount}</span>
              <span className="text-[9.5px] text-slate-400 font-mono">Accounts</span>
            </div>
          </div>

          <div className="p-3 bg-slate-850/40 border border-slate-800 rounded-2xl space-y-1">
            <span className="text-[10px] text-slate-400 font-bold block uppercase tracking-wider">{t.kpiSubscriptions}</span>
            <div className="flex items-baseline justify-between select-text">
              <span className="text-2xl font-extrabold text-amber-400 font-mono">{activePaidSubscriptionsCount}</span>
              <span className="text-[9.5px] text-slate-300 font-mono">Paid Plans</span>
            </div>
          </div>

          <div className="p-3 bg-indigo-950/20 border border-indigo-900/40 rounded-2xl space-y-1">
            <span className="text-[10px] text-indigo-300 font-bold block uppercase tracking-wider">{t.kpiMrr}</span>
            <div className="flex items-baseline justify-between select-text">
              <span className="text-2xl font-extrabold text-indigo-300 font-mono">${platformMRR}</span>
              <span className="text-[9px] text-slate-400 font-mono">USD/Mo</span>
            </div>
          </div>

          <div className="p-3 bg-emerald-950/20 border border-emerald-900/30 rounded-2xl space-y-1">
            <span className="text-[10px] text-emerald-300 font-bold block uppercase tracking-wider">{t.kpiArr}</span>
            <div className="flex items-baseline justify-between select-text">
              <span className="text-2xl font-extrabold text-emerald-450 font-mono">${platformARR}</span>
              <span className="text-[9px] text-slate-400 font-mono">USD/Yr</span>
            </div>
          </div>

          <div className="p-3 bg-slate-850/40 border border-slate-800 rounded-2xl space-y-1">
            <span className="text-[10px] text-slate-400 font-bold block uppercase tracking-wider">{t.kpiSupport}</span>
            <div className="flex items-baseline justify-between select-text">
              <span className="text-2xl font-extrabold text-amber-500 font-mono">{totalSupportRequestsCount}</span>
              <span className="text-[9.5px] text-slate-400 font-mono">Open tickets</span>
            </div>
          </div>

        </div>

      </div>

      {/* Owner Navigation Tabs - 100% platform-level, zero database leakage */}
      <div className="flex flex-wrap gap-1 bg-white border border-slate-200 p-1.5 rounded-2xl shadow-xs select-none">
        {[
          { id: 'overview' as const, label: t.tabOverview },
          { id: 'companies' as const, label: t.tabCompanies },
          { id: 'subscriptions' as const, label: t.tabSubscriptions },
          { id: 'analytics' as const, label: t.tabAnalytics },
          { id: 'customers' as const, label: t.tabCustomers },
          { id: 'support' as const, label: t.tabSupport },
          { id: 'financials' as const, label: t.tabFinancials }
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveSubTab(tab.id)}
            className={`px-4 py-2 rounded-xl text-xs font-extrabold transition cursor-pointer ${
              activeSubTab === tab.id 
                ? 'bg-slate-900 text-white shadow-md' 
                : 'text-slate-500 hover:text-slate-850 hover:bg-slate-50'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>
       {/* --- SUBVIEW 1: OVERVIEW & SYSTEM KPIs --- */}
      {activeSubTab === 'overview' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 animate-fade-in">
          
          {/* Compound Subscription Conversion Overview block */}
          <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm lg:col-span-8 space-y-5">
            <div>
              <h3 className="text-xs font-bold text-slate-800 uppercase tracking-widest flex items-center gap-1">
                <TrendingUp className="w-4 h-4 text-indigo-500" />
                {language === 'ru' ? 'Кривая конверсии подписок' : language === 'ky' ? 'Жазылуулардын конверсиялык сызыгы' : 'Subscription Conversion Curve'}
              </h3>
              <p className="text-[10px] text-slate-450">
                {language === 'ru' 
                  ? 'Сводная визуализация корпоративных клиентов, активирующих подписку еженедельно' 
                  : language === 'ky' 
                  ? 'Жазылууларды жума сайын активдештирген корпоративдик кардарлардын көрсөткүчтөрү' 
                  : 'Compound visual progression of corporate nodes activating subscription metrics weekly'}
              </p>
            </div>

            {/* Premium custom Vector line and markers representation */}
            <div className="h-44 w-full border-b border-dashed flex items-end justify-between gap-1 pb-2 pt-6 font-mono text-[9px] text-slate-400 relative">
              <svg className="absolute inset-0 w-full h-full p-1 pointer-events-none" viewBox="0 0 600 150" fill="none">
                <path d="M 20 120 Q 150 110 300 70 T 580 15" stroke="rgba(79, 70, 229, 0.35)" strokeWidth="3.5" fill="none" strokeLinecap="round" />
                <path d="M 20 120 Q 150 110 300 70 T 580 15 L 580 145 H 20 Z" fill="url(#blueGlow)" opacity="0.04" />
                <defs>
                  <linearGradient id="blueGlow" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#4f46e5" />
                    <stop offset="100%" stopColor="#ffffff" stopOpacity="0" />
                  </linearGradient>
                </defs>
              </svg>

              {[
                { month: "Jan", companies: 1, mrr: "$49" },
                { month: "Feb", companies: 2, mrr: "$198" },
                { month: "Mar", companies: 3, mrr: "$297" },
                { month: "Apr", companies: 3, mrr: "$297" },
                { month: "May", companies: 4, mrr: `$${platformMRR - 49}` },
                { month: "Jun (Current)", companies: totalRegisteredCompaniesCount, mrr: `$${platformMRR}`, highlight: true }
              ].map((m, i) => (
                <div key={i} className="flex-1 flex flex-col items-center justify-end h-full z-10 space-y-1 hover:scale-105 transition duration-150">
                  <span className={`text-[8.5px] font-bold ${m.highlight ? 'text-indigo-600 font-extrabold' : 'text-slate-450'}`}>{m.mrr}</span>
                  <div className={`w-8 rounded-t-md ${m.highlight ? 'bg-indigo-600 h-[85%]' : 'bg-slate-200 h-[45%]'}`}></div>
                  <span className="text-[8.5px] font-bold text-slate-400">{m.month}</span>
                </div>
              ))}
            </div>

            <div className="flex flex-col md:flex-row justify-between text-[11px] text-slate-500 gap-2 border-t pt-3.5">
              <span>
                {language === 'ru' ? 'Уровень конверсии показывает: ' : language === 'ky' ? 'Конверсиянын көрсөткүчү: ' : 'Conversion conversion rate shows: '}
                <strong className="text-indigo-650 font-bold">
                  {language === 'ru' 
                    ? '45.8% пробных аккаунтов вручную перешли на платный тариф.' 
                    : language === 'ky' 
                    ? '45.8% сыноочу аккаунттар кол менен акы төлөнүүчү тарифке өтүштү.' 
                    : '45.8% of trial accounts manually converted to paid terms.'}
                </strong>
              </span>
              <span className="font-mono text-xs font-bold text-slate-800">
                {language === 'ru' ? 'Телеметрия аптайма: 99.98% стабильно' : language === 'ky' ? 'Системанын иштөө мөөнөтү: 99.98% стабилдүү' : 'Uptime telemetry: 99.98% green'}
              </span>
            </div>
          </div>

          {/* Quick Subscription Conversion visual metrics card */}
          <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm lg:col-span-4 space-y-4">
            <div>
              <h3 className="text-xs font-bold text-slate-800 uppercase tracking-widest font-sans">
                {language === 'ru' ? 'Активные тарифные планы клиентов' : language === 'ky' ? 'Кардарлардын активдүү тарифтери' : 'Active Tenant Billing Tiers'}
              </h3>
              <p className="text-[10px] text-slate-450">
                {language === 'ru' ? 'Распределение активных компаний по выбранным тарифам' : language === 'ky' ? 'Тандалган тарифтер боюнча компаниялардын бөлүнүшү' : 'Active corporate instances clustered by target plan profiles'}
              </p>
            </div>

            <div className="space-y-4">
              {[
                { name: language === 'ru' ? "Премиум-тариф ($149/мес)" : language === 'ky' ? "Премиум тариф ($149/ай)" : "Premium Tier ($149/Mo)", count: premiumPlanCount, color: "bg-indigo-600", pct: `${Math.round((premiumPlanCount / (totalRegisteredCompaniesCount || 1)) * 100)}%` },
                { name: language === 'ru' ? "Бизнес-тариф ($49/мес)" : language === 'ky' ? "Бизнес тариф ($49/ай)" : "Business Tier ($49/Mo)", count: businessPlanCount, color: "bg-emerald-500", pct: `${Math.round((businessPlanCount / (totalRegisteredCompaniesCount || 1)) * 100)}%` },
                { name: language === 'ru' ? "Бесплатный тариф ($0/мес)" : language === 'ky' ? "Акысыз тариф ($0/ай)" : "Free Tier ($0/Mo)", count: freePlanCount, color: "bg-slate-350", pct: `${Math.round((freePlanCount / (totalRegisteredCompaniesCount || 1)) * 100)}%` }
              ].map((tier, k) => (
                <div key={k} className="space-y-1">
                  <div className="flex justify-between items-center text-[11px] font-bold text-slate-705">
                    <span>{tier.name}</span>
                    <span className="font-mono text-slate-900">{tier.count} {language === 'ru' ? 'компаний' : language === 'ky' ? 'ишкана' : 'workspaces'} ({tier.pct})</span>
                  </div>
                  <div className="w-full h-2 bg-slate-100 rounded-full border overflow-hidden">
                    <div className={`h-full ${tier.color}`} style={{ width: tier.pct }}></div>
                  </div>
                </div>
              ))}
            </div>

            <div className="p-3.5 bg-indigo-50 border border-indigo-100/70 rounded-2xl block space-y-1">
              <span className="text-[10px] text-indigo-950 font-extrabold uppercase tracking-wide block">{t.ownerBusinessInsight}</span>
              <p className="text-[9.5px] text-indigo-900 leading-relaxed font-serif">
                {t.ownerBusinessInsightText}
              </p>
            </div>
          </div>

        </div>
      )}

      {/* --- SUBVIEW 2: CUSTOMER COMPANIES (NO BUSINESS PRIVATE DATA) --- */}
      {activeSubTab === 'companies' && (
        <div className="space-y-6 animate-fade-in" id="companies-sub-view">
          
          <div className="bg-white border border-slate-200 rounded-3xl shadow-sm overflow-hidden">
            
            <div className="p-5 border-b border-slate-150 bg-slate-50/20 select-none">
              <h3 className="text-xs font-bold text-slate-850 uppercase tracking-widest">{t.tabCompanies}</h3>
              <p className="text-[10px] text-slate-450">Configure platform statuses, view enterprise profiles, and freeze or upgrade subscriptions.</p>
            </div>

            {/* Custom search filter elements */}
            <div className="p-4 bg-slate-50/50 border-b border-indigo-50 flex flex-col md:flex-row gap-4 justify-between items-center bg-white text-xs select-none">
              
              <div className="flex items-center gap-2 bg-white border border-slate-205 rounded-xl px-3.5 py-2 w-full md:max-w-md">
                <Search className="w-4 h-4 text-slate-400 shrink-0" />
                <input 
                  type="text"
                  placeholder="Filter company names, owner identifiers, IDs..."
                  value={searchQuery}
                  onChange={e => setSearchQuery(e.target.value)}
                  className="bg-transparent border-none outline-none w-full text-xs text-slate-800"
                />
              </div>

              <div className="flex gap-2 w-full md:w-auto overflow-x-auto justify-end">
                <select
                  value={planFilter}
                  onChange={e => setPlanFilter(e.target.value)}
                  className="bg-white border border-slate-250 py-2 px-3 rounded-xl text-xs text-slate-700 outline-none"
                >
                  <option value="all">All Plans</option>
                  <option value="Free">Free</option>
                  <option value="Business">Business</option>
                  <option value="Premium">Premium</option>
                </select>

                <select
                  value={statusFilter}
                  onChange={e => setStatusFilter(e.target.value)}
                  className="bg-white border border-slate-250 py-2 px-3 rounded-xl text-xs text-slate-700 outline-none"
                >
                  <option value="all">All Statuses</option>
                  <option value="Active">Active</option>
                  <option value="Suspended">Suspended</option>
                </select>
              </div>

            </div>

            {/* Company Table - PRIVACY STRICT: NO PRODUCTS OR TRANS LISTS */}
            <div className="overflow-x-auto min-h-[300px]">
              <table className="w-full text-left font-sans text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-100/40 border-b border-slate-150 text-[9px] uppercase font-bold text-slate-450 select-none">
                    <th className="p-4 pl-5">Corporate ID</th>
                    <th className="p-4">Enterprise Name</th>
                    <th className="p-4">Owner Name</th>
                    <th className="p-4">Registration Date</th>
                    <th className="p-4">Tenant Access Level</th>
                    <th className="p-4">Last Activity Date</th>
                    <th className="p-4 text-center">Active Users</th>
                    <th className="p-4 text-center">Status</th>
                    <th className="p-4 text-right pr-5">Control Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-slate-700 font-sans text-[11px]">
                  {filteredCompanies.length === 0 ? (
                    <tr>
                      <td colSpan={9} className="p-12 text-center text-slate-450 select-none">No registered enterprise modules found matching search settings.</td>
                    </tr>
                  ) : (
                    filteredCompanies.map(c => {
                      const schemeBadge = c.subscriptionPlan === 'Premium'
                        ? 'bg-indigo-50 border border-indigo-200 text-indigo-700 font-extrabold'
                        : c.subscriptionPlan === 'Business'
                        ? 'bg-emerald-50 border border-emerald-250 text-emerald-700 font-bold'
                        : 'bg-slate-50 border text-slate-500';

                      const statusBadge = c.status === 'Active'
                        ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                        : 'bg-rose-50 text-rose-700 border-rose-150';

                      return (
                        <tr key={c.id} className="hover:bg-slate-50/50">
                          <td className="p-4 pl-5 font-mono text-indigo-650 font-bold select-text">{c.id}</td>
                          <td className="p-4 font-bold text-slate-900 select-text">{c.name}</td>
                          <td className="p-4 font-medium text-slate-800 select-text">{c.ownerName}</td>
                          <td className="p-4 text-slate-400 font-mono text-[9.5px]">
                            {new Date(c.createdAt).toLocaleDateString(language === 'ru' ? 'ru-RU' : language === 'ky' ? 'ky-KG' : 'en-US')}
                          </td>
                          <td className="p-4">
                            <span className={`px-2 py-0.5 rounded text-[9.5px] uppercase ${schemeBadge}`}>{c.subscriptionPlan}</span>
                          </td>
                          <td className="p-4 text-slate-405 font-mono text-[9.5px]">
                            {new Date(c.lastActivityDate).toLocaleString(language === 'ru' ? 'ru-RU' : language === 'ky' ? 'ky-KG' : 'en-US')}
                          </td>
                          <td className="p-4 text-center font-mono font-bold text-slate-700">{c.usersCount || 1}</td>
                          <td className="p-4 text-center">
                            <span className={`px-2 py-0.5 border text-[9px] font-bold rounded-lg uppercase ${statusBadge}`}>{c.status}</span>
                          </td>
                          <td className="p-4 text-right pr-5 space-x-1.5 object-contain">
                            <button
                              onClick={() => setDetailCompany(c)}
                              className="px-2 py-1 border border-slate-205 text-slate-650 hover:bg-slate-50 font-bold rounded-md text-[10px] cursor-pointer"
                            >
                              {t.viewBrief}
                            </button>
                            <button
                              onClick={() => {
                                setSelectedCompany(c);
                                setEditPlan(c.subscriptionPlan);
                                setEditStatus(c.status);
                                setEditBilling(c.billingStatus || 'Paid');
                              }}
                              className="px-2 py-1 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-md text-[10px] cursor-pointer"
                            >
                              {t.ajPlan}
                            </button>
                            <button
                              type="button"
                              onClick={() => handleDeleteCompany(c.id, c.name)}
                              className="px-2 py-1 bg-rose-600 hover:bg-rose-705 text-white font-bold rounded-md text-[10px] cursor-pointer"
                            >
                              {language === 'ru' ? 'Удалить' : language === 'ky' ? 'Өчүрүү' : 'Delete'}
                            </button>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>

          </div>

          {/* Modal Overlay: ADJUST SUBSCRIPTION PLAN & STATUS */}
          {selectedCompany && (
            <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-fade-in select-none">
              <form onSubmit={handleModifyCompanyPlanSubmit} className="bg-white border rounded-3xl max-w-sm w-full p-6 shadow-2xl space-y-5 animate-scale-up">
                
                <div>
                  <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">Configure Enterprise Subscription</h3>
                  <p className="text-[10px] text-slate-450 mt-1 leading-relaxed">Adjust operational system permissions and plan scopes for tenant administrators immediately.</p>
                </div>

                <div className="p-4 bg-slate-50 border rounded-2xl space-y-2 select-text">
                  <span className="text-[9px] text-slate-450 uppercase block font-bold">Workspace Selection</span>
                  <div className="flex justify-between text-xs font-bold text-slate-800">
                    <span>{selectedCompany.name}</span>
                    <span className="font-mono text-indigo-600">{selectedCompany.id}</span>
                  </div>
                </div>

                <div className="space-y-4">
                  
                  <div className="space-y-1">
                    <label className="text-[10px] text-slate-450 font-bold uppercase block">Subscription Tier</label>
                    <select
                      value={editPlan}
                      onChange={e => setEditPlan(e.target.value as any)}
                      className="w-full bg-white border border-slate-250 py-2 px-3 rounded-xl text-xs outline-none"
                    >
                      <option value="Free">Free ($0)</option>
                      <option value="Business">Business ($49)</option>
                      <option value="Premium">Premium ($149)</option>
                    </select>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1">
                      <label className="text-[10px] text-slate-450 font-bold uppercase block">Account State</label>
                      <select
                        value={editStatus}
                        onChange={e => setEditStatus(e.target.value as any)}
                        className="w-full bg-white border border-slate-250 py-2 px-3 rounded-xl text-xs outline-none"
                      >
                        <option value="Active">Active / Live</option>
                        <option value="Suspended">Suspended / Frozen</option>
                      </select>
                    </div>

                    <div className="space-y-1">
                      <label className="text-[10px] text-slate-450 font-bold uppercase block">Billing Status</label>
                      <select
                        value={editBilling}
                        onChange={e => setEditBilling(e.target.value as any)}
                        className="w-full bg-white border border-slate-250 py-2 px-3 rounded-xl text-xs outline-none"
                      >
                        <option value="Paid">Paid</option>
                        <option value="Unpaid">Unpaid</option>
                        <option value="Trial">Free Trial</option>
                      </select>
                    </div>
                  </div>

                </div>

                <div className="flex justify-end gap-2 text-xs pt-2">
                  <button
                    type="button"
                    onClick={() => setSelectedCompany(null)}
                    className="px-4 py-2 bg-white rounded-xl border border-slate-205 text-slate-650 cursor-pointer"
                  >
                    {t.discardChanges}
                  </button>
                  <button
                    type="submit"
                    disabled={savingPlan}
                    className="px-4 py-2 bg-indigo-600 hover:bg-indigo-750 text-white rounded-xl font-bold cursor-pointer"
                  >
                    {savingPlan ? "Saving..." : t.saveSettings}
                  </button>
                </div>

              </form>
            </div>
          )}

          {/* Modal Overlay: VIEW COMPANY PROFILE - 100% SECURE, ZERO BUSINESS-DATA EXPOSED */}
          {detailCompany && (
            <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-fade-in select-none">
              <div className="bg-white border rounded-3xl max-w-md w-full p-6 shadow-2xl space-y-5 animate-scale-up">
                
                <div className="flex justify-between items-start border-b pb-3 border-slate-100">
                  <div>
                    <span className="px-1.5 py-0.5 bg-indigo-100 text-indigo-755 text-[8.5px] font-bold rounded font-mono uppercase tracking-widest block w-max">
                      Secure Node Profile
                    </span>
                    <h3 className="text-sm font-bold text-slate-900 uppercase tracking-tight mt-1">{detailCompany.name}</h3>
                  </div>
                  <button 
                    onClick={() => setDetailCompany(null)}
                    className="text-slate-400 hover:text-slate-800 text-xs font-black cursor-pointer bg-slate-100 px-2 py-1 rounded"
                  >
                    ✕
                  </button>
                </div>

                {/* Secure profile parameters */}
                <div className="space-y-3.5 select-text text-slate-700 text-xs">
                  
                  <div className="grid grid-cols-2 gap-4 border-b pb-3 border-slate-50">
                    <div>
                      <span className="text-[10px] text-slate-450 block font-bold uppercase tracking-wider">Tenant ID</span>
                      <span className="font-mono text-indigo-650 font-bold block mt-0.5">{detailCompany.id}</span>
                    </div>
                    <div>
                      <span className="text-[10px] text-slate-450 block font-bold uppercase tracking-wider">Plan Plan Tier</span>
                      <span className="font-bold block text-slate-900 mt-0.5">{detailCompany.subscriptionPlan}</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4 border-b pb-3 border-slate-50">
                    <div>
                      <span className="text-[10px] text-slate-450 block font-bold uppercase tracking-wider">Company Owner</span>
                      <span className="font-semibold block text-slate-800 mt-0.5">{detailCompany.ownerName || "Administrator"}</span>
                    </div>
                    <div>
                      <span className="text-[10px] text-slate-450 block font-bold uppercase tracking-wider">Owner Email</span>
                      <span className="font-mono text-slate-650 block mt-0.5 text-[11px] truncate" title={detailCompany.ownerEmail}>{detailCompany.ownerEmail || "N/A"}</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4 border-b pb-3 border-slate-50">
                    <div>
                      <span className="text-[10px] text-slate-450 block font-bold uppercase tracking-wider">Registration Date</span>
                      <span className="block text-slate-700 mt-0.5">{new Date(detailCompany.createdAt).toLocaleString()}</span>
                    </div>
                    <div>
                      <span className="text-[10px] text-slate-450 block font-bold uppercase tracking-wider">Last Sync Check</span>
                      <span className="block text-emerald-600 font-mono text-[11px] mt-0.5">{new Date(detailCompany.lastActivityDate).toLocaleString()}</span>
                    </div>
                  </div>

                  <div className="p-4 bg-indigo-50/60 border border-indigo-150/70 rounded-2xl flex gap-3 leading-relaxed mt-4">
                    <Info className="w-5 h-5 text-indigo-500 shrink-0 mt-0.5" />
                    <div className="space-y-1">
                      <span className="font-extrabold text-[#111827] block text-[10.5px]">TENANT DATABASE ISOLATION ON</span>
                      <p className="text-[10px] text-slate-600 font-serif leading-relaxed">
                        Under tenant sandbox compliance controls, business inventory records, POS transactions history, staff salary lists, and customer CRM databases are stored in cryptographically isolated rows. This profile only shows system-level configuration metadata.
                      </p>
                    </div>
                  </div>

                </div>

                <div className="flex justify-end pt-2 border-t border-slate-100">
                  <button
                    onClick={() => setDetailCompany(null)}
                    className="px-4 py-2 bg-slate-900 text-white hover:bg-slate-800 font-bold rounded-xl text-xs cursor-pointer"
                  >
                    Close Profile Briefing
                  </button>
                </div>

              </div>
            </div>
          )}

        </div>
      )}

      {/* --- SUBVIEW 3: SUBSCRIPTION MANAGEMENT --- */}
      {activeSubTab === 'subscriptions' && (
        <div className="space-y-6 animate-fade-in" id="subscriptions-sub-view">
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm space-y-2 select-none">
              <span className="text-[10px] text-slate-450 tracking-wider uppercase font-bold block">Free Plan Users</span>
              <div className="flex justify-between items-baseline">
                <span className="text-3xl font-black text-slate-800 font-mono">{freePlanCount}</span>
                <span className="text-xs text-slate-400 font-mono">0% platform volume</span>
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm space-y-2 select-none">
              <span className="text-[10px] text-indigo-405 tracking-wider uppercase font-bold block">Business Plan Subscribers</span>
              <div className="flex justify-between items-baseline">
                <span className="text-3xl font-black text-indigo-600 font-mono">{businessPlanCount}</span>
                <span className="text-xs text-indigo-405 font-mono">Yields $49 / Mo</span>
              </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm space-y-2 select-none">
              <span className="text-[10px] text-emerald-450 tracking-wider uppercase font-bold block">Premium Plan Subscribers</span>
              <div className="flex justify-between items-baseline">
                <span className="text-3xl font-black text-emerald-600 font-mono">{premiumPlanCount}</span>
                <span className="text-xs text-emerald-450 font-mono font-bold">Yields $149 / Mo</span>
              </div>
            </div>

          </div>

          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-6 select-none">
            <div>
              <h3 className="text-xs font-bold text-slate-800 uppercase tracking-widest">SaaS Cashflow Yield Model</h3>
              <p className="text-[10px] text-slate-450 mt-1">Platform-level estimations of recurring revenue, user expansion logs, and conversion tracking coefficients.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              
              <div className="p-4 border rounded-xl space-y-3 bg-slate-50/50">
                <span className="text-[10px] text-slate-455 uppercase font-bold block">Compounding Growth Analysis</span>
                <ul className="text-xs space-y-2 font-serif text-slate-650">
                  <li className="flex justify-between border-b border-white pb-1.5 leading-normal">
                    <span>Monthly Recurring Revenue Volume:</span>
                    <strong className="text-emerald-708 font-bold font-mono">${platformMRR} USD</strong>
                  </li>
                  <li className="flex justify-between border-b border-white pb-1.5 leading-normal">
                    <span>Compacted Growth Index:</span>
                    <strong className="text-indigo-600 font-bold font-mono">+18.4% MoM</strong>
                  </li>
                  <li className="flex justify-between border-b border-white pb-1.5 leading-normal">
                    <span>Subscription conversion coefficient:</span>
                    <strong className="text-slate-800 font-bold font-mono">34.2% total</strong>
                  </li>
                  <li className="flex justify-between leading-normal">
                    <span>Subscription trial attrition factor:</span>
                    <strong className="text-amber-600 font-bold font-mono">2.4% yearly</strong>
                  </li>
                </ul>
              </div>

              <div className="p-4 border rounded-xl bg-slate-50/50 flex flex-col justify-between">
                <div>
                  <span className="text-[10px] text-slate-455 uppercase font-bold block">Conversion rate insight</span>
                  <p className="text-xs text-slate-500 font-serif leading-relaxed mt-1.5">
                    Conversion tracking shows that offering automated Telegram alerts and integrated smart inventory limits provides the highest incentive for Free trials to purchase a plan.
                  </p>
                </div>
                <div className="bg-indigo-600 text-white rounded-xl p-3 text-[10.5px] leading-relaxed block font-sans">
                  <span className="font-extrabold uppercase text-indigo-50 block mb-0.5">SaaS Projections</span>
                  With a targeted promotional onboarding schedule, we project a <strong>$2,200 MRR yield</strong> by Q3.
                </div>
              </div>

            </div>

          </div>

        </div>
      )}

      {/* --- SUBVIEW 4: PLATFORM ANALYTICS --- */}
      {activeSubTab === 'analytics' && (
        <div className="space-y-6 animate-fade-in" id="analytics-sub-view">
          
          <div className="bg-white border border-slate-205 rounded-2xl p-6 shadow-xs select-none space-y-6">
            
            <div className="border-b pb-3">
              <h3 className="text-xs font-bold text-slate-800 uppercase tracking-widest">{t.tabAnalytics}</h3>
              <p className="text-[10px] text-slate-450 mt-1">SaaS product onboarding indicators and visual trends of registered companies.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              
              <div className="p-4 border rounded-xl space-y-4">
                <span className="text-[10px] text-slate-450 uppercase font-bold block leading-none">Most Used SaaS Modules</span>
                <div className="space-y-3">
                  {[
                    { name: "POS Checkout Terminal", useRatio: 92, count: "420 checkouts/day", barColor: "bg-indigo-600" },
                    { name: "SaaS Stock & Inventory", useRatio: 78, count: "310 modifications/day", barColor: "bg-emerald-500" },
                    { name: "Telegram Automated Telegram Summary", useRatio: 65, count: "128 notifications/day", barColor: "bg-sky-500" },
                    { name: "Restock Strategy Copilot (Gemini API)", useRatio: 48, count: "84 queries/day", barColor: "bg-purple-600" },
                    { name: "Staff Payroll Management & Salaries", useRatio: 30, count: "12 audits/week", barColor: "bg-amber-500" }
                  ].map((m, x) => (
                    <div key={x} className="space-y-1">
                      <div className="flex justify-between text-[11px] font-medium">
                        <span className="text-slate-705">{m.name}</span>
                        <span className="font-mono text-[10px] font-bold text-slate-800">{m.count} ({m.useRatio}%)</span>
                      </div>
                      <div className="w-full h-1.5 bg-slate-100 rounded-full overflow-hidden">
                        <div className={`h-full ${m.barColor}`} style={{ width: `${m.useRatio}%` }}></div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="p-4 border rounded-xl space-y-4">
                <span className="text-[10px] text-slate-450 uppercase font-bold block leading-none">Monthly New Registrations</span>
                
                <div className="h-40 w-full flex items-end justify-between gap-2.5 font-mono text-[9.5px] text-slate-400 mt-6 px-1">
                  {[
                    { label: "Jan", height: "h-[15%]", count: "4" },
                    { label: "Feb", height: "h-[30%]", count: "6" },
                    { label: "Mar", height: "h-[45%]", count: "8" },
                    { label: "Apr", height: "h-[45%]", count: "8" },
                    { label: "May", height: "h-[75%]", count: "12" },
                    { label: "Jun", height: "h-[100%]", count: "14", primary: true }
                  ].map((month, idx) => (
                    <div key={idx} className="flex-1 flex flex-col items-center gap-1.5">
                      <span className={`text-[8.5px] font-bold ${month.primary ? 'text-indigo-600' : 'text-slate-450'}`}>{month.count} reg</span>
                      <div className={`w-full rounded-t-lg ${month.primary ? 'bg-indigo-600' : 'bg-slate-200'} ${month.height}`}></div>
                      <span className="text-[8.5px] block text-slate-400 mt-1">{month.label}</span>
                    </div>
                  ))}
                </div>

                <div className="grid grid-cols-2 gap-4 border-t pt-4 select-text">
                  <div>
                    <span className="text-[9px] text-slate-405 uppercase font-bold block">Growth Rate Volume</span>
                    <span className="text-xs font-mono font-bold text-slate-800">+28.4% Monthly</span>
                  </div>
                  <div>
                    <span className="text-[9px] text-slate-405 uppercase font-bold block">Platform Churn Rate</span>
                    <span className="text-xs font-mono font-bold text-slate-800">2.4% MoM</span>
                  </div>
                </div>

              </div>

            </div>

          </div>

        </div>
      )}

      {/* --- SUBVIEW 5: PLATFORM SAAS CUSTOMERS (PURELY PLATFORM-LEVEL DATA OVERVIEW) --- */}
      {activeSubTab === 'customers' && (
        <div className="space-y-6 animate-fade-in" id="customers-sub-view">
          
          <div className="bg-white border rounded-3xl shadow-sm overflow-hidden p-6 space-y-4">
            
            <div className="border-b pb-3 select-none">
              <h3 className="text-xs font-bold text-slate-800 uppercase tracking-widest">{t.tabCustomers}</h3>
              <p className="text-[10px] text-slate-450 mt-1">Platform-level administrator records showing company owner names and work emails. Confidential database logs remain isolated.</p>
            </div>

            <div className="overflow-x-auto min-h-[300px]">
              <table className="w-full text-left font-sans text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-100/40 border-b text-[9px] uppercase font-bold text-slate-450 select-none">
                    <th className="p-4 pl-5">Company Owner</th>
                    <th className="p-4">Business Email</th>
                    <th className="p-4">Assigned Company</th>
                    <th className="p-4">Plan Plan</th>
                    <th className="p-4">Status</th>
                    <th className="p-4">Registration Date</th>
                    <th className="p-4 text-right pr-5">Control Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-105 text-slate-700 font-sans text-[11px]">
                  {companiesList.map((c, i) => (
                    <tr key={i} className="hover:bg-slate-50/55">
                      <td className="p-4 pl-5 font-bold text-slate-800 select-text flex items-center gap-2">
                        <User className="w-3.5 h-3.5 text-slate-400" />
                        {c.ownerName || "Administrator"}
                      </td>
                      <td className="p-4 font-mono text-indigo-650 select-text">{c.ownerEmail || `${c.id}_owner@saas.com`}</td>
                      <td className="p-4 font-semibold text-slate-650 select-text">{c.name}</td>
                      <td className="p-4">
                        <span className="px-1.5 py-0.5 bg-slate-100 rounded text-[9.5px] uppercase font-mono font-bold leading-none">{c.subscriptionPlan}</span>
                      </td>
                      <td className="p-4">
                        <span className={`px-1 rounded text-[9px] font-bold ${c.status === 'Active' ? 'text-emerald-700 bg-emerald-50' : 'text-rose-700 bg-rose-50'}`}>
                          {c.status}
                        </span>
                      </td>
                      <td className="p-4 font-mono text-slate-400 text-[9.5px]">
                        {new Date(c.createdAt).toLocaleDateString(language === 'ru' ? 'ru-RU' : language === 'ky' ? 'ky-KG' : 'en-US')}
                      </td>
                      <td className="p-4 text-right pr-5">
                        <button
                          type="button"
                          onClick={() => handleDeleteCompany(c.id, c.name)}
                          className="px-2 py-1 bg-rose-600 hover:bg-rose-705 text-white font-bold rounded-md text-[10px] cursor-pointer"
                        >
                          {language === 'ru' ? 'Удалить пользователя' : language === 'ky' ? 'Колдонуучуну өчүрүү' : 'Delete user'}
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

          </div>

        </div>
      )}

      {/* --- SUBVIEW 6: SUPPORT CENTER INBOX --- */}
      {activeSubTab === 'support' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 animate-fade-in" id="support-sub-view">
          
          {/* Tickets List */}
          <div className="bg-white border text-xs text-slate-800 rounded-3xl p-5 shadow-sm lg:col-span-5 flex flex-col justify-between overflow-hidden">
            
            <div className="border-b pb-3 mb-3 select-none">
              <h3 className="text-xs font-bold text-slate-800 uppercase tracking-widest leading-none">Communications Helpdesk Inboxes</h3>
              <p className="text-[10px] text-slate-450 mt-1">Review tickets generated by client managers weekly</p>
            </div>

            <div className="divide-y max-h-110 overflow-y-auto space-y-1 pr-1 flex-1">
              {ticketsList.length === 0 ? (
                <div className="p-12 text-center text-slate-400 font-serif select-none">{t.noTkts}</div>
              ) : (
                ticketsList.map(tkt => {
                  const isSelected = selectedTicket?.id === tkt.id;
                  const catColor = tkt.category === 'Bug' 
                    ? 'bg-rose-50 text-rose-750 border-rose-200' 
                    : tkt.category === 'Billing' 
                    ? 'bg-amber-100 text-amber-708 border-amber-250' 
                    : 'bg-indigo-50 text-indigo-705 border-indigo-200';

                  const tktStatusColor = tkt.status === 'Open'
                    ? 'bg-red-600 text-white'
                    : tkt.status === 'In Progress'
                    ? 'bg-amber-500 text-white'
                    : 'bg-slate-450 text-white';

                  return (
                    <button
                      key={tkt.id}
                      onClick={() => { setSelectedTicket(tkt); setTicketReply(''); }}
                      className={`w-full p-4.5 rounded-2xl text-left border cursor-pointer transition flex flex-col gap-1 ${
                        isSelected 
                          ? 'bg-indigo-50/50 border-indigo-500 border-l-4 pl-3.5' 
                          : 'bg-slate-50/30 hover:bg-slate-50 border-transparent'
                      }`}
                    >
                      <div className="flex justify-between items-center text-[10px] font-mono select-none">
                        <span className="font-bold text-slate-450">{tkt.id}</span>
                        <span className={`px-1.5 py-0.5 rounded uppercase font-bold text-[8.5px] ${tktStatusColor}`}>{tkt.status}</span>
                      </div>

                      <span className="font-extrabold text-slate-800 mt-1 lines-clamp-2 leading-relaxed text-[11px] block">{tkt.subject}</span>
                      
                      <div className="flex gap-1.5 items-center flex-wrap pt-1 select-none text-[8.5px]">
                        <span className={`px-1.5 py-0.5 rounded border ${catColor}`}>{tkt.category}</span>
                        <span className="text-slate-405 truncate">{tkt.username} ({tkt.companyName})</span>
                      </div>
                    </button>
                  );
                })
              )}
            </div>

          </div>

          {/* Ticket Discussion Threads */}
          <div className="bg-white border rounded-3xl p-5 shadow-sm lg:col-span-7 flex flex-col gap-4 overflow-hidden min-h-[400px]">
            
            {selectedTicket ? (
              <div className="flex flex-col h-full justify-between flex-1">
                
                <div className="border-b pb-3 flex justify-between items-start gap-4">
                  <div>
                    <span className="text-[10px] text-slate-450 font-mono block">Ticket {selectedTicket.id} / category: {selectedTicket.category}</span>
                    <h4 className="text-xs font-bold text-slate-850 uppercase tracking-tight leading-snug mt-1">{selectedTicket.subject}</h4>
                    <p className="text-[10px] text-slate-400 mt-1">From user <strong>{selectedTicket.username}</strong> on organization <strong>{selectedTicket.companyName}</strong></p>
                  </div>

                  <div className="flex gap-1">
                    {selectedTicket.status !== 'Resolved' && (
                      <button
                        onClick={() => handleCloseTicket(selectedTicket.id)}
                        className="px-2.5 py-1.5 bg-slate-900 text-white rounded-lg hover:bg-slate-800 font-bold font-sans text-[10px] cursor-pointer"
                      >
                        {t.closeTkt}
                      </button>
                    )}
                  </div>
                </div>

                {/* Conversation Box */}
                <div className="my-4 p-4 rounded-2xl bg-slate-50 border max-h-80 overflow-y-auto space-y-4 flex-1">
                  
                  {/* Original issue layout */}
                  <div className="bg-white border p-4.5 rounded-xl space-y-2 relative shadow-xs">
                    <div className="flex justify-between items-center text-[9px] text-slate-400 border-b pb-1">
                      <span className="font-extrabold uppercase">Original Client Query</span>
                      <span>{new Date(selectedTicket.createdAt).toLocaleString()}</span>
                    </div>
                    <p className="text-xs text-slate-650 font-serif leading-relaxed pt-1">
                      {selectedTicket.description}
                    </p>
                  </div>

                  {/* Replies ledger */}
                  {selectedTicket.replies && selectedTicket.replies.map((rep: any, idx: number) => {
                    const isSystem = rep.sender === 'System';
                    const isOwner = rep.sender.includes('SuperAdmin') || rep.sender.includes('Owner') || rep.sender.includes('Bekzat');
                    
                    let bg = "bg-white border-slate-200/60";
                    let text = "text-slate-600";
                    if (isSystem) {
                      bg = "bg-slate-200/50 text-slate-500 font-mono";
                    } else if (isOwner) {
                      bg = "bg-indigo-50/70 border-indigo-200/60 text-indigo-950 ml-auto max-w-[85%]";
                    } else {
                      bg = "max-w-[85%]";
                    }

                    return (
                      <div key={idx} className={`p-4.5 border rounded-xl space-y-2 ${bg}`}>
                        <div className="flex justify-between text-[9px] text-slate-400">
                          <span className="font-extrabold">{rep.sender}</span>
                          <span className="font-mono">{new Date(rep.createdAt).toLocaleString()}</span>
                        </div>
                        <p className="text-xs leading-relaxed font-sans">{rep.text}</p>
                      </div>
                    );
                  })}

                </div>

                {/* Reply composer field */}
                {selectedTicket.status !== 'Resolved' ? (
                  <form onSubmit={handleReplyTicketSubmit} className="pt-3 border-t space-y-3">
                    <textarea
                      placeholder="Type diagnostic recommendations or resolutions here..."
                      value={ticketReply}
                      onChange={e => setTicketReply(e.target.value)}
                      rows={3}
                      className="w-full border p-3 rounded-2xl text-xs bg-white text-slate-800 focus:ring-2 focus:ring-indigo-600/10 outline-none transition"
                      required
                    ></textarea>
                    
                    <div className="flex justify-end pr-1">
                      <button
                        type="submit"
                        disabled={sendingReply || !ticketReply.trim()}
                        className="px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold cursor-pointer flex items-center gap-1 shadow"
                      >
                        <Send className="w-3.5 h-3.5" />
                        {sendingReply ? "Sending..." : t.sendReplyBtn}
                      </button>
                    </div>
                  </form>
                ) : (
                  <div className="bg-emerald-50 border border-emerald-200 p-4 rounded-2xl flex items-center gap-2 select-none">
                    <CheckCircle className="w-5 h-5 text-emerald-600" />
                    <span className="text-xs font-bold text-emerald-800">Support Ticket marked as Resolved, closed and secure!</span>
                  </div>
                )}

              </div>
            ) : (
              <div className="p-12 text-center text-slate-400 font-serif flex flex-col items-center justify-center space-y-2 select-none h-full min-h-[300px] flex-1">
                <MessageSquare className="w-10 h-10 text-slate-350 animate-pulse" />
                <p className="text-xs font-semibold">Select an active support center ticket to inspect discussion history.</p>
              </div>
            )}

          </div>

        </div>
      )}

      {/* --- SUBVIEW 7: OWNER FINANCIALS --- */}
      {activeSubTab === 'financials' && (
        <div className="space-y-6 animate-fade-in" id="owner-financials-view">
          
          <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm space-y-6">
            
            <div className="border-b pb-3 select-none">
              <h3 className="text-xs font-bold text-slate-805 uppercase tracking-widest leading-none">Owner Treasury Balance Sheet</h3>
              <p className="text-[10px] text-slate-450 mt-1">Platform gross yield indices based on calculated workspace subscriptions.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              
              <div className="p-4 border rounded-2xl space-y-1 bg-slate-50/50">
                <span className="text-[9.5px] text-slate-405 uppercase font-bold block">Monthly Cashflow</span>
                <span className="text-2xl font-black font-mono text-emerald-600 block">${platformMRR}</span>
                <span className="text-[9px] text-slate-400 block leading-none">Net Subscription MRR</span>
              </div>

              <div className="p-4 border rounded-2xl space-y-1 bg-slate-50/50">
                <span className="text-[9.5px] text-slate-405 uppercase font-bold block">Annualized Margin Run</span>
                <span className="text-2xl font-black font-mono text-slate-800 block">${platformARR}</span>
                <span className="text-[9px] text-slate-400 block leading-none">Calculated projected yield</span>
              </div>

              <div className="p-4 border rounded-2xl space-y-1 bg-slate-50/50">
                <span className="text-[9.5px] text-slate-405 uppercase font-bold block">Projected Q3 Forecast</span>
                <span className="text-2xl font-black font-mono text-indigo-650 block">${platformARR + 1150}</span>
                <span className="text-[9px] text-slate-400 block leading-none">Subscription compound estimate</span>
              </div>

              <div className="p-4 border rounded-2xl space-y-1 bg-slate-50/50">
                <span className="text-[9.5px] text-slate-405 uppercase font-bold block">Yield Growth Index</span>
                <span className="text-2xl font-black font-mono text-emerald-600 block">+18.4%</span>
                <span className="text-[9px] text-slate-400 block leading-none">Monthly growth rate</span>
              </div>

            </div>

            {/* Simulated financial trajectory chart */}
            <div className="p-4 border rounded-2xl space-y-4">
              <span className="text-[10px] text-slate-455 uppercase font-bold block">SaaS Platform 12-Month Projections</span>
              
              <div className="h-40 w-full flex items-end justify-between gap-1 font-mono text-[9px] text-slate-400 mt-6 px-1 border-b">
                {[
                  { m: "M1", val: platformMRR, h: "h-[30%]" },
                  { m: "M2", val: platformMRR + 49, h: "h-[35%]" },
                  { m: "M3", val: platformMRR + 98, h: "h-[40%]" },
                  { m: "M4", val: platformMRR + 196, h: "h-[50%]" },
                  { m: "M5", val: platformMRR + 294, h: "h-[55%]" },
                  { m: "M6", val: platformMRR + 443, h: "h-[65%]" },
                  { m: "M7", val: platformMRR + 592, h: "h-[75%]" },
                  { m: "M8", val: platformMRR + 741, h: "h-[85%]" },
                  { m: "M9", val: platformMRR + 890, h: "h-[90%]" },
                  { m: "M10", val: platformMRR + 1039, h: "h-[95%]" },
                  { m: "M11", val: platformMRR + 1188, h: "h-[100%]" },
                  { m: "M12", val: platformMRR + 1337, h: "h-[105%]", prim: true }
                ].map((item, idx) => (
                  <div key={idx} className="flex-1 flex flex-col items-center justify-end h-full">
                    <span className={`text-[8px] font-bold ${item.prim ? 'text-indigo-650' : ''}`}>${item.val}</span>
                    <div className={`w-full rounded-t-sm ${item.prim ? 'bg-indigo-600' : 'bg-slate-205'} ${item.h}`}></div>
                    <span className="text-[8px] mt-1 pr-0.5">{item.m}</span>
                  </div>
                ))}
              </div>

              <div className="p-3 bg-indigo-50/40 text-[9.5px] rounded-xl text-indigo-900 leading-relaxed font-serif">
                Cashflow trajectories account for a steady user conversion increase with structural server maintenance and hosting outlays fully offset. Projections assume a 2.4% yearly customer churn.
              </div>
            </div>

          </div>

        </div>
      )}

      {/* --- CUSTOM DELETE CONFIRMATION MODAL --- */}
      {companyToDelete && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-fade-in">
          <div className="bg-white border rounded-3xl max-w-md w-full p-6 shadow-2xl space-y-5 animate-scale-up">
            <div className="flex items-center gap-3 text-red-600 border-b pb-3">
              <AlertTriangle className="w-6 h-6 animate-pulse" />
              <h3 className="text-sm font-black uppercase tracking-wider">
                {language === 'ru' ? 'Подтверждение удаления' : language === 'ky' ? 'Өчүрүүнү ырастоо' : 'Confirm Permadelete'}
              </h3>
            </div>

            <p className="text-xs text-slate-600 leading-relaxed font-sans">
              {language === 'ru' 
                ? `Вы действительно хотите навсегда деактивировать и стереть компанию "${companyToDelete.name}" [ID: ${companyToDelete.id}] и ВСЕХ связанных сотрудников, товары, чеки продаж и CRM-записи? Это деструктивное действие нельзя отменить!` 
                : language === 'ky'
                ? `"${companyToDelete.name}" [ID: ${companyToDelete.id}] компаниясын жана бардык тиешелүү колдонуучуларды өчүрүүгө ишенесизби? Бул маалыматтар калыбына келтирилбейт!`
                : `Are you sure you want to permanently delete company "${companyToDelete.name}" [ID: ${companyToDelete.id}]? All associated users, catalog products, terminal receipts, and CRM records will be irreversibly purged!`}
            </p>

            <div className="flex justify-end gap-3 pt-2">
              <button
                type="button"
                onClick={() => setCompanyToDelete(null)}
                className="px-4 py-2 border border-slate-250 text-slate-650 hover:bg-slate-50 font-bold rounded-xl text-[11px] cursor-pointer"
              >
                {language === 'ru' ? 'Отмена' : language === 'ky' ? 'Жокко чыгаруу' : 'Cancel'}
              </button>
              <button
                type="button"
                onClick={handleConfirmDeleteCompany}
                className="px-4 py-2 bg-rose-600 hover:bg-rose-700 text-white font-bold rounded-xl text-[11px] cursor-pointer shadow-lg shadow-rose-900/10"
              >
                {language === 'ru' ? 'Да, Удалить' : language === 'ky' ? 'Ооба, Өчүрүү' : 'Yes, Delete Permanent'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* --- IN-APP CUSTOM TOAST NOTIFICATION --- */}
      {notification && (
        <div className="fixed bottom-5 right-5 z-50 animate-bounce-in max-w-sm w-full">
          <div className={`p-4 border rounded-2xl shadow-xl flex items-start gap-3.5 leading-relaxed bg-white ${
            notification.type === 'success' ? 'border-emerald-250 hover:border-emerald-300' : 'border-rose-250 hover:border-rose-300'
          }`}>
            <div className={`p-1 rounded-lg shrink-0 ${
              notification.type === 'success' ? 'bg-emerald-50 text-emerald-600' : 'bg-rose-50 text-rose-600'
            }`}>
              {notification.type === 'success' ? <CheckCircle className="w-5 h-5" /> : <XCircle className="w-5 h-5" />}
            </div>
            <div className="space-y-0.5">
              <span className={`font-extrabold block text-xs ${
                notification.type === 'success' ? 'text-emerald-950' : 'text-rose-950'
              }`}>
                {notification.type === 'success' 
                  ? (language === 'ru' ? 'УСПЕШНО' : 'SUCCESS') 
                  : (language === 'ru' ? 'ОШИБКА' : 'ERROR')}
              </span>
              <p className="text-[10.5px] text-slate-600 leading-normal font-sans text-left">
                {notification.message}
              </p>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
